### ISSUE TITLE
Get frontend ready to deploy

### ISSUE THREAD

**Issue by ejanzer** [codeforsanjose/open-disclosure#169]
Issues we want to fix before deploying the frontend:
- [x] Switch all candidate UI over to using TotalRCPT instead of TotalFunding (Funding includes LOAN, but this is inconsistent with aggregate data showed elsewhere) #172
- [x] Show a minimum "sliver" in the bar chart if the % is too small #170 
- [x] Update text for Committees section on Candidates page (committees are not owned by candidate) #170
- [x] Remove See All Contributions link for now #170
- [x] Add SJ to geo breakdown #170
- [x] Scroll issue with nav bar #168
- [x] Remove 'get notified of updates' in noData.js
- [x] Fix About Us page

**Comment by alessandro-pianetta** [comment]
React-Axe Errors:

## index.js
### Serious
- [ ] Documents must have `<title>` element to aid in navigation
- [ ] `<html>` element must have a lang attribute
- [ ] `<ul>` and `<ol>` must only directly contain `<li>`, `<script>` or `<template>` elements 
### Moderate

- [ ] Heading levels should only increase by one
- [ ] Document must have one main landmark
- [ ] Ensures landmarks are unique
- [ ] All page content must be contained by landmarks
